sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


before_script:
  - apt-get install ffmpeg
  - apt-get install youtube-dl
  - ln -s `which youtube-dl` /usr/local/bin/youtube-dl
  - ln -s `which ffmpeg` /usr/local/bin/ffmpeg
  - ln -s `which ffprobe` /usr/local/bin/ffprobe
  - ./gradlew npmInstall

script:
  - ./gradlew docker


after_success:
  - docker login  -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag  lumue/woelkchen_download:master-SNAPSHOT lumue/woelkchen_download:latest
  - docker push lumue/woelkchen_download:master-SNAPSHOT
  - docker push lumue/woelkchen_download:latest

