woelkchen_download:
  image: lumue/woelkchen_download:master-SNAPSHOT
  restart: always

  volumes:
    - /data/docker-volumes/woelkchen_download/woelkchen_download:/woelkchen_download
    - /mnt/nasbox/media:/downloads
  ports:
    - "7001:8001"

